# AI 推理优化配置文件
# 基于 docs/ai_optimization_architecture.md 的完整配置

# TensorRT 推理引擎配置
tensorrt:
  enable: true
  enable_fp16: true
  enable_int8: false
  max_batch_size: 4
  max_workspace_size: 1073741824  # 1GB
  fp16_threshold: 0.1
  device_id: 0
  enable_profiling: false
  num_inference_threads: 1

# NAM 注意力机制配置
nam_attention:
  enable: true
  # 通道注意力参数
  channel_reduction_ratio: 16.0
  channel_gamma: 2.0
  channel_beta: 4.0
  
  # 空间注意力参数
  spatial_kernel_size: 7.0
  spatial_gamma: 2.0
  spatial_beta: 4.0
  
  # 归一化参数
  normalization_epsilon: 1e-5
  use_batch_norm: true
  use_layer_norm: false
  
  # 训练参数
  learning_rate: 1e-4
  weight_decay: 1e-4
  enable_dropout: true
  dropout_rate: 0.1

# GhostConv 配置 (减少卷积计算量)
ghost_conv:
  enable: true
  reduction_ratio: 2
  kernel_size: 1
  use_depthwise: true

# VoV-GSCSP 配置 (压缩颈部)
vov_gscsp:
  enable: true
  groups: 1
  expansion: 0.5
  kernel_size: 1

# Wise-IoU 损失函数配置
wise_iou:
  enable: true
  alpha: 1.0
  beta: 1.0
  gamma: 1.0
  delta: 1.0
  eps: 1e-7
  use_focal: true
  focal_alpha: 0.25
  focal_gamma: 2.0
  use_giou: false
  use_diou: false
  use_ciou: false


# SAHI 切片推理配置
sahi_slicing:
  enable: true
  slice_height: 512
  slice_width: 512
  overlap_ratio: 0.2
  confidence_threshold: 0.5
  merge_strategy: "WEIGHTED_AVERAGE"  # NMS, WEIGHTED_AVERAGE, CONFIDENCE_BASED, HYBRID
  slice_strategy: "ADAPTIVE"  # GRID, RANDOM, ADAPTIVE, PYRAMID

# 摄像头硬件加速配置
hardware_acceleration:
  enable: true
  acceleration_type: "V4L2_HW"  # NONE, V4L2_HW, GSTREAMER_HW, CUDA_HW, MIXED_HW
  enable_zero_copy: true
  enable_isp: true
  enable_async_capture: true
  enable_hardware_codec: true

# 检测器优化配置
detector_optimization:
  # 模型配置
  model_path: "/opt/bamboo-cut/models/bamboo_detector.onnx"
  input_width: 640
  input_height: 640
  
  # 检测参数
  confidence_threshold: 0.5
  nms_threshold: 0.4
  max_detections: 100
  
  # 优化级别
  optimization_level: 2  # 0-3, 0=基础, 3=最高
  enable_noise_reduction: true
  
  # 批处理优化
  enable_batch_processing: true
  batch_size: 4
  enable_async_processing: true
  num_worker_threads: 4
  
  # 3D 深度检测
  enable_stereo_depth: true
  
  # 启用的优化技术
  enable_tensorrt: true
  enable_fp16: true
  enable_nam_attention: true
  enable_ghost_conv: true
  enable_vov_gscsp: true
  enable_wise_iou: true
  enable_sahi_slicing: true
  enable_hardware_acceleration: true

# 性能监控配置
performance_monitoring:
  enable_stats: true
  stats_interval_ms: 1000
  enable_profiling: true
  log_performance_stats: true
  save_stats_to_file: true
  stats_file_path: "/opt/bamboo-cut/logs/performance_stats.json"

# 调试和日志配置
debugging:
  enable_debug_mode: false
  log_level: "INFO"  # DEBUG, INFO, WARN, ERROR
  save_intermediate_results: false
  debug_output_path: "/opt/bamboo-cut/debug/"