# 显示系统配置文件
# 支持DRM和Wayland双模式渐进式迁移

display:
  # 显示后端选择
  # - auto: 自动检测（优先Wayland，回退到DRM）
  # - drm: 直接DRM模式（原有模式）
  # - wayland: Wayland客户端模式（新模式）
  backend: auto
  
  # 屏幕分辨率
  resolution:
    width: 1280
    height: 800
    
  # 刷新率
  refresh_rate: 60
  
  # DRM特定配置
  drm:
    device_path: "/dev/dri/card1"
    fallback_devices:
      - "/dev/dri/card0" 
      - "/dev/dri/card2"
    color_depth: 32
    
  # Wayland特定配置
  wayland:
    socket_name: "wayland-bamboo"
    compositor_cmd: "weston --backend=drm-backend.so --tty=7"
    enable_gpu_acceleration: true
    client_timeout: 5000  # ms
    
    # 窗口布局配置
    layout:
      lvgl_window:
        x: 0
        y: 0
        width: 1280
        height: 800
        z_order: 1
        
      video_window:
        x: 0
        y: 80        # header下方
        width: 960   # 75%宽度
        height: 640  # 主要区域
        z_order: 2

# DeepStream视频流配置
deepstream:
  # 视频输出模式
  # - nv3dsink: 窗口模式（与LVGL共存）
  # - nvdrmvideosink: DRM叠加平面模式（独立显示层）
  # - waylandsink: Wayland客户端模式
  output_mode: nvdrmvideosink  # 默认使用DRM叠加平面模式
  
  # nvdrmvideosink配置（DRM叠加平面模式）
  nvdrmvideosink:
    # DRM叠加平面设置
    plane_id: -1          # -1表示自动检测可用平面
    connector_id: -1      # -1表示自动检测连接器
    crtc_id: -1          # -1表示自动检测CRTC
    z_order: 1           # Z轴层级（1=在LVGL之上，0=在LVGL之下）
    enable_scaling: true # 启用硬件缩放
    
    # 显示位置（相对于整个屏幕）
    offset_x: 0
    offset_y: 80         # header下方
    width: 960           # 75%宽度
    height: 640          # 主要区域
    
    # 性能设置
    sync: false          # 降低延迟
    set_mode: false      # 不改变显示模式
    show_preroll_frame: false  # 不显示预览帧
    
  # nv3dsink配置（窗口模式，作为回退方案）
  nv3dsink:
    sync: false
    window_x: 0
    window_y: 80
    window_width: 960
    window_height: 640
    
  # waylandsink配置（Wayland模式）
  waylandsink:
    display: "wayland-bamboo"
    x: 0
    y: 80
    width: 960
    height: 640

# 叠加平面层级管理
overlay_planes:
  # 系统保留的叠加平面
  reserved_planes:
    - 0  # 主平面，用于LVGL界面
  
  # 可用于视频的叠加平面
  available_planes:
    - 1  # 视频叠加平面1
    - 2  # 视频叠加平面2（如果可用）
  
  # 层级优先级（数值越大越靠前）
  z_order_mapping:
    lvgl_ui: 0        # LVGL界面层
    video_overlay: 1  # 视频叠加层
    cursor: 2         # 鼠标光标层

# 显示层级分离配置
display_separation:
  # 启用独立显示层
  enable_layer_separation: true
  
  # LVGL层配置
  lvgl_layer:
    plane_type: "primary"    # 主平面
    z_order: 0
    format: "ARGB8888"
    
  # 视频层配置
  video_layer:
    plane_type: "overlay"    # 叠加平面
    z_order: 1
    format: "NV12"
    enable_alpha: false      # 视频不需要透明度
  
  # 错误处理
  fallback_on_error: true
  max_retry_attempts: 3
  
  # 性能监控
  performance_monitor:
    enable: true
    fps_threshold: 25  # 最低FPS要求
    latency_threshold: 50  # ms
    layer_conflict_detection: true  # 检测层级冲突